id: A3E9FF322
title: Threefold Aspiration for Rebirth in Zangdok Palri
type: translation
pechas:
- I3793CFA4
- I8887CC22
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:13.493086
  last_modified_at: 2023-01-04 11:32:13.493098
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I3793CFA4/646F: 0A74
  I8887CC22/8353: 0A74
